vich_uploader:
  db_driver: orm

  mappings:
      Rapport:
          uri_prefix: /images/Rapport
          upload_destination: '%kernel.project_dir%/public/images/Rapport'

          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true