vich_uploader:
    db_driver: orm

    mappings:
        compterendu_image:
            uri_prefix: public/images/
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        proposition_image:
                uri_prefix: public/images/
                upload_destination: '%kernel.project_dir%/public/images/'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        backlog_image:
          uri_prefix: public/images/
          upload_destination: '%kernel.project_dir%/public/images/'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        sprint_image:
          uri_prefix: public/images/
          upload_destination: '%kernel.project_dir%/public/images/'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer