vich_uploader:
    db_driver: orm

    mappings:
        compterendu_image:
            uri_prefix: public/images/
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        proposition_image:
                uri_prefix: public/images/
                upload_destination: '%kernel.project_dir%/public/images/'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        backlog_image:
          uri_prefix: public/images/
          upload_destination: '%kernel.project_dir%/public/images/'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        sprint_image:
          uri_prefix: public/images/
          upload_destination: '%kernel.project_dir%/public/images/'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        Rapport:
          uri_prefix: /images/Rapport
          upload_destination: '%kernel.project_dir%/public/images/Rapport'

          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true